/**
 * 常用服务
 * useful server
 */
export const us = {
  data:[
    {
      title:"日报",
      icon:"/static/icon/daycall.png",
      description:"记录每天的工作经验和心得",
      useCount:1000
    },{
      title:"周报",
      icon:"/static/icon/week.png",
      description:"总结每周的工作情况和下周计划",
      useCount:10000
    },{
      title:"考勤",
      icon:"/static/icon/kaoqin.png",
      description:"工作考勤",
      page:'clockHome',
      useCount:10000
    },{
      title:"日程",
      icon:"/static/icon/richeng.png",
      description:"建立和查看个人工作安排",
      useCount:10000,
      page:'planList'
    },{
      title:"请假申请",
      icon:"/static/icon/liucheng.png",
      description:"请假申请",
      useCount:10000,
      page:'leave'
    },
      {
          title:"出差申请",
          icon:"/static/icon/liucheng.png",
          description:"出差申请",
          useCount:10000,
          page:'businesStrip'
      },
      {
          title:"公文发文",
          icon:"/static/icon/liucheng.png",
          description:"公文发文",
          useCount:10000,
          page:'docSend'
      },
      {
          title:"通知公告",
          icon:"/static/icon/tongzhi.png",
          description:"查看企业对员工下发的通知公告",
          useCount:10000,
          page:'annotationList'
    },{
          title:"内部邮件",
          icon:"/static/icon/duanxin.png",
          description:"查看内部消息",
          useCount:10000,
          page:'mailHome',
          dot:false
      },{
          title:"通讯录",
          icon:"/static/icon/duanxin.png",
          description:"查看部门，组员",
          useCount:10000,
          page:'communication',
      }
  ]
}


/**
 * other server 其他服务
 */
export const os = {
  data:[
    {
      title:"新闻中心",
      icon:"/static/icon/daycall.png",
      description:"新闻中心",
      page:'columnList',
      useCount:10000
    },{
      title:"投票中心",
      icon:"/static/icon/week.png",
      description:"投票中心",
      useCount:10000
    },{
      title:"任务中心",
      icon:"/static/icon/kaoqin.png",
      description:"任务中心",
      useCount:10000
    },{
      title:"文档中心",
      icon:"/static/icon/richeng.png",
      description:"文档中心",
      useCount:10000,
      page:'fileHome'
    },{
      title:"合同",
      icon:"/static/icon/liucheng.png",
      description:"合同",
      useCount:10000
    },{
      title:"会议",
      icon:"/static/icon/tongzhi.png",
      description:"会议",
      useCount:10000
    },{
      title:"客户关系",
      icon:"/static/icon/duanxin.png",
      description:"客户关系",
      useCount:10000
    }
  ]
}